<?php


/**
 * Test class for Robo47_DirectoryHasher.
 * Generated by PHPUnit on 2012-01-09 at 05:19:48.
 */
class Robo47_DirectoryHasherTest extends PHPUnit_Framework_TestCase {

    /**
     * @var Robo47_DirectoryHasher
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new Robo47_DirectoryHasher;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers {className}::{origMethodName}
     * @todo Implement testRun().
     */
    public function testRun() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers {className}::{origMethodName}
     * @todo Implement testGetResult().
     */
    public function testGetResult() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}

?>
