<?php


/**
 * Test class for Robo47_DirectoryHasher_Hasher_Multi.
 * Generated by PHPUnit on 2012-01-09 at 05:19:51.
 */
class Robo47_DirectoryHasher_Hasher_MultiTest extends PHPUnit_Framework_TestCase {

    /**
     * @var Robo47_DirectoryHasher_Hasher_Multi
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new Robo47_DirectoryHasher_Hasher_Multi;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers {className}::{origMethodName}
     * @todo Implement testAddHashsToFileResult().
     */
    public function testAddHashsToFileResult() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers {className}::{origMethodName}
     * @todo Implement testAddHashsToResult().
     */
    public function testAddHashsToResult() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}

?>
